import { useEffect, useMemo, useRef, useState } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { Archive, ArrowLeft } from 'lucide-react'
import { PageHeader } from '@/components/shared/PageHeader'
import { Button, buttonVariants } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { CardStatic } from '@/components/ui/card'
import { PricingApiError, pricingClient } from '@/lib/pricing-client'
import { dispositionAcknowledgement, dispositionProposal, dispositionReady, dispositionReply, pendingDispositionKey, savePendingDisposition, validateDispositionBasis, type DispositionDraft, type DispositionPreview, type PendingDisposition } from '@/lib/outcome-disposition-form'
import { CorrectionBudget, CorrectionCost } from './correction-impact'
import { CostFacts } from './cost-metadata'
import { PriceField, PriceSelect } from './pricing-fields'
import { PriceCostBreakdown, PricingDiagnostics, pricingErrorKey } from './price-simulator'
import { usePricingNavigationState } from './pricing-navigation-guard'
import type { OutcomeDispositionBasis, OutcomeDispositionInput, OutcomeDispositionResult, OutcomeDispositionAction } from '@/types/pricing'

export function OutcomeDispositionNotice(){const {t}=useTranslation('pricing');return <div className="border-l-2 border-amber-500 bg-amber-500/5 px-4 py-3 text-sm leading-6"><p className="font-semibold">{t('disposition.warning')}</p><p>{t('disposition.budgetBoundary')}</p></div>}
export function OutcomeDispositionEditor({workspace,actor,outcomeId,initial,pending,storageInvalid,canManage}:{workspace:string;actor:string;outcomeId:string;initial:OutcomeDispositionBasis|null;pending:PendingDisposition|null;storageInvalid:boolean;canManage:boolean}){
  const {t}=useTranslation('pricing'),cache=useQueryClient(),request=useMemo(()=>pricingClient(workspace),[workspace]),prefix=`/runtime-outcomes/${encodeURIComponent(outcomeId)}`
  const [basis,setBasis]=useState(()=>initial?structuredClone(initial):null),[draft,setDraft]=useState<DispositionDraft>(()=>pending?{action:pending.proposal.action,reason:pending.proposal.reason}:{action:'',reason:''})
  const [review,setReview]=useState<{proposal:OutcomeDispositionInput;preview:DispositionPreview}|null>(()=>pending?{proposal:pending.proposal,preview:pending.preview}:null),[recorded,setRecorded]=useState<DispositionPreview|null>(null)
  const [phase,setPhase]=useState<'editable'|'uncertain'|'conflict'|'resolved'>(pending?'uncertain':storageInvalid?'conflict':'editable'),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[checked,setChecked]=useState(false),[error,setError]=useState<unknown>(null),[storageError,setStorageError]=useState(storageInvalid)
  const active=useRef<AbortController|null>(null),feedback=useRef<HTMLDivElement|null>(null),impact=useRef<HTMLDivElement|null>(null)
  useEffect(()=>()=>active.current?.abort(),[])
  useEffect(()=>{if(error||storageError||phase!=='editable'){feedback.current?.scrollIntoView({block:'center'});feedback.current?.focus({preventScroll:true})}},[error,storageError,phase])
  useEffect(()=>{if(review&&phase==='editable'){impact.current?.scrollIntoView({block:'start'});impact.current?.focus({preventScroll:true})}},[review,phase])
  const release=usePricingNavigationState(phase!=='resolved'&&(draft.action!==''||draft.reason!==''||review!==null),busy||phase==='uncertain')
  const locked=!canManage||busy||phase!=='editable'||storageError||!basis||Boolean(basis.blocked_reason)
  const start=()=>{if(active.current)return null;const controller=new AbortController();active.current=controller;setBusy(true);setError(null);return controller}
  const finish=(controller:AbortController)=>{if(active.current===controller){active.current=null;if(!controller.signal.aborted)setBusy(false)}}
  const clear=()=>{try{sessionStorage.removeItem(pendingDispositionKey(workspace,actor,outcomeId));setStorageError(false)}catch{setStorageError(true)}}
  const edit=(value:DispositionDraft)=>{if(locked)return;setDraft(value);setReview(null);setConfirmed(false);setError(null)}
  const complete=(preview:DispositionPreview)=>{clear();setRecorded(preview);setConfirmed(false);setPhase('resolved');release();for(const queryKey of [['pricing',workspace],['logs'],['logs-summary'],['budget']])void cache.invalidateQueries({queryKey})}
  const preview=async()=>{
    if(locked||!basis||!dispositionReady(basis,draft))return;const controller=start();if(!controller)return;setConfirmed(false)
    try{const proposal=dispositionProposal(basis,draft),value=await request<OutcomeDispositionResult>(`${prefix}/disposition/preview`,proposal,'POST',controller.signal);const result=await dispositionReply(value,proposal,workspace,actor,outcomeId,basis.request_id,true,basis);if(!controller.signal.aborted)setReview({proposal,preview:result})}
    catch(failure){if(!controller.signal.aborted){setError(failure);setReview(null);if(failure instanceof PricingApiError&&failure.status===409)setPhase('conflict')}}finally{finish(controller)}
  }
  const apply=async()=>{
    if(!canManage||!review||!confirmed||storageError||!['editable','uncertain'].includes(phase))return;const controller=start();if(!controller)return
    try{savePendingDisposition(sessionStorage,{version:1,workspace,actor,outcomeId,...review})}catch{setStorageError(true);finish(controller);return}
    const uncertain=phase==='uncertain'
    try{const value=await request<OutcomeDispositionResult>(`${prefix}/disposition`,review.proposal,'POST',controller.signal),result=await dispositionReply(value,review.proposal,workspace,actor,outcomeId,review.preview.requestId,false,review.preview);if(!controller.signal.aborted)complete(result)}
    catch(failure){if(!controller.signal.aborted){setError(failure);setConfirmed(false);setChecked(false);if(!uncertain&&failure instanceof PricingApiError&&failure.status>=400&&failure.status<500&&failure.code!=='workspace_changed'){clear();setPhase('conflict')}else setPhase('uncertain')}}finally{finish(controller)}
  }
  const check=async()=>{
    const operationId=review?.proposal.id??basis?.disposition?.id;if(!operationId)return;const controller=start();if(!controller)return
    try{const value=await request<{recorded:boolean;result:OutcomeDispositionResult}>(`${prefix}/dispositions/${encodeURIComponent(operationId)}`,undefined,'GET',controller.signal);if(value.recorded!==true)throw new Error('invalid_outcome_disposition');const preview=review?await dispositionReply(value.result,review.proposal,workspace,actor,outcomeId,review.preview.requestId,false,review.preview):await dispositionAcknowledgement(value.result,basis!,workspace);if(!controller.signal.aborted)complete(preview)}
    catch(failure){if(!controller.signal.aborted){if(phase==='uncertain'&&failure instanceof PricingApiError&&failure.status===404){setChecked(true);setError(null)}else setError(failure)}}finally{finish(controller)}
  }
  const reread=async()=>{
    if(phase==='uncertain'&&(!checked||!window.confirm(t('usageRecovery.abandon'))))return;if(storageError&&!window.confirm(t('recovery.clearStorageConfirm')))return;const controller=start();if(!controller)return
    try{const next=await validateDispositionBasis(await request<OutcomeDispositionBasis>(`${prefix}/disposition-basis`,undefined,'GET',controller.signal),outcomeId);if(!controller.signal.aborted){clear();setBasis(next);setReview(null);setConfirmed(false);setChecked(false);setPhase('editable')}}catch(failure){if(!controller.signal.aborted)setError(failure)}finally{finish(controller)}
  }
  const effect=recorded??review?.preview
  return <div className="space-y-5"><PageHeader title={t('disposition.reviewTitle')} description={t('disposition.reviewHelp')} icon={Archive}><Link to="/pricing/outcomes" className={buttonVariants({variant:'outline'})}><ArrowLeft className="h-4 w-4" />{t('disposition.back')}</Link></PageHeader><OutcomeDispositionNotice />
    <CostFacts items={[[t('disposition.outcomeId'),<code>{outcomeId}</code>],[t('cost.request'),<code>{basis?.request_id??review?.preview.requestId??'—'}</code>],[t('disposition.outcomeHash'),<code>{basis?.outcome_hash??review?.proposal.expected_outcome_hash??'—'}</code>],[t('recovery.proposal'),<code>{review?.proposal.id??basis?.disposition?.id??'—'}</code>]]} />
    <div ref={feedback} tabIndex={-1} aria-live="polite" className="space-y-3 outline-none">{error!=null&&<p role="alert" className="border-l-2 border-red-500 p-4 text-sm leading-6">{t(error instanceof Error&&['invalid_outcome_disposition','invalid_attempt_correction','invalid_usage_recovery'].includes(error.message)?'usageRecovery.invalidReply':phase==='uncertain'?'recovery.uncertainTitle':pricingErrorKey(error))}</p>}{error instanceof PricingApiError&&<PricingDiagnostics diagnostics={error.diagnostics} />}{storageError&&<p role="alert">{t('recovery.storageError')}</p>}
      {phase==='conflict'&&<p role="status" className="border-l-2 border-amber-500 p-4 text-sm leading-6">{t('disposition.conflict')}</p>}
      {phase==='uncertain'&&<CardStatic className="space-y-3 p-5"><h2 className="font-semibold">{t(pending?'recovery.pendingRestored':'recovery.uncertainTitle')}</h2><p className="text-sm leading-6">{t('recovery.uncertain')}</p><Button variant="outline" disabled={busy} onClick={()=>void check()}>{t('recovery.checkStatus')}</Button>{checked&&<p className="text-xs leading-6">{t('recovery.notRecorded')}</p>}</CardStatic>}
      {(phase==='conflict'||(phase==='uncertain'&&checked)||storageError||(phase==='editable'&&basis?.blocked_reason&&basis.blocked_reason!=='already_disposed'))&&<Button variant="outline" disabled={busy} onClick={()=>void reread()}>{t('recovery.reread')}</Button>}
      {phase==='resolved'&&<CardStatic className="space-y-3 p-5"><h2 className="font-semibold">{t('disposition.success')}</h2><p className="text-sm leading-6">{t('disposition.successHelp')}</p></CardStatic>}
    </div>
    {!canManage&&<p className="text-sm">{t('disposition.inspectOnly')}</p>}
    {basis?.blocked_reason&&phase==='editable'&&<p role="status" className="border-l-2 border-amber-500 px-4 py-3 text-sm">{t(['already_disposed','not_review_required'].includes(basis.blocked_reason)?`disposition.block.${basis.blocked_reason}`:`attemptCorrection.block.${basis.blocked_reason}`)}</p>}
    {basis?.disposition&&phase==='editable'&&<CardStatic className="space-y-3 p-5"><p>{t(`disposition.decision.${basis.disposition.action}`)}</p><CostFacts items={[[t('cost.actor'),basis.disposition.actor_id],[t('recovery.proposal'),<code>{basis.disposition.id}</code>]]} /><Button variant="outline" disabled={busy} onClick={()=>void check()}>{t('recovery.checkStatus')}</Button></CardStatic>}
    {basis&&phase!=='resolved'&&<DispositionEvidence key={basis.basis_hash} basis={basis} />}
    {canManage&&phase!=='resolved'&&!basis?.disposition&&<CardStatic className="space-y-4 p-5"><PriceSelect label={t('disposition.action')} value={draft.action} disabled={locked} options={[{value:'',label:t('disposition.choose')},...(['accept_receipts','reject_evidence'] as OutcomeDispositionAction[]).map(value=>({value,label:t(`disposition.action.${value}`)}))]} onChange={action=>edit({...draft,action:action as DispositionDraft['action']})} /><p className="text-sm leading-6">{t(draft.action==='reject_evidence'?'disposition.rejectHelp':'disposition.acceptHelp')}</p><PriceField label={t('correction.reason')}>{id=><textarea id={id} value={draft.reason} disabled={locked} maxLength={1000} className="min-h-24 w-full rounded-lg border border-[var(--border)] bg-[var(--background-secondary)] p-3 text-sm" onChange={event=>edit({...draft,reason:event.target.value})} />}</PriceField><p className="text-xs leading-6 text-[var(--foreground-muted)]">{t('disposition.storage')}</p><Button variant="outline" disabled={locked||!dispositionReady(basis,draft)} onClick={()=>void preview()}>{t('disposition.preview')}</Button></CardStatic>}
    {effect&&<div ref={impact} tabIndex={-1} className="space-y-5 outline-none"><h2 className="text-lg font-semibold">{t(phase==='resolved'?'disposition.recordedImpact':'disposition.impact')}</h2><Badge variant="amber">{t(phase==='resolved'?`disposition.decision.${effect.action}`:`disposition.proposed.${effect.action}`)}</Badge>{effect.action==='reject_evidence'?<CardStatic className="p-5 text-sm leading-6">{t('disposition.rejectHelp')}</CardStatic>:effect.receipts.map((row,index)=><CardStatic key={row.attemptId} className="space-y-5 p-5"><h3 className="break-all text-sm font-semibold">{index+1}. <code>{row.attemptId}</code></h3><p>{t(`disposition.operation.${row.operation}`)}</p><div className="grid min-w-0 gap-6 xl:grid-cols-2">{row.before?<CorrectionCost cost={row.before} title={t('attemptCorrection.before')} />:<section><h4 className="font-semibold">{t('attemptCorrection.before')}</h4><p className="mt-3 text-sm">{t('disposition.noReceipt')}</p></section>}<CorrectionCost cost={row.after} title={t('disposition.selectedReceipt')} /></div><p className="text-xs leading-6">{t(row.originalErrorPreserved?'disposition.originalError':'disposition.initialError')}: <code>{row.errorCode??'—'}</code></p><CorrectionBudget budget={row.budget} applied={phase==='resolved'} /></CardStatic>)}</div>}
    {canManage&&review&&['editable','uncertain'].includes(phase)&&<CardStatic className="space-y-4 p-5"><label className="flex items-start gap-3 text-sm leading-6"><input type="checkbox" checked={confirmed} disabled={busy} className="mt-1.5" onChange={event=>setConfirmed(event.target.checked)} />{t(phase==='uncertain'?'disposition.confirmRetry':review.proposal.action==='reject_evidence'?'disposition.confirmReject':'disposition.confirmAccept')}</label><Button disabled={busy||!confirmed||storageError} onClick={()=>void apply()}>{t(busy?'working':phase==='uncertain'?'recovery.retry':'disposition.apply')}</Button></CardStatic>}
  </div>
}
function DispositionEvidence({basis}:{basis:OutcomeDispositionBasis}){
  const {t}=useTranslation('pricing'),[page,setPage]=useState(0),size=10
  return <><CardStatic className="space-y-4 p-5"><h2 className="font-semibold">{t('disposition.evidence',{count:basis.receipts.length})}</h2><p className="text-sm leading-6">{t('disposition.membersHelp')}</p>{!basis.receipts.length&&<p>{t('disposition.noReceipts')}</p>}{basis.receipts.slice(page*size,(page+1)*size).map((row,index)=><details key={row.attempt_id} className="min-w-0 border-t border-[var(--border)] pt-4"><summary className="cursor-pointer break-all text-sm font-semibold">{page*size+index+1}. <code>{row.attempt_id}</code></summary><div className="mt-4 space-y-5"><CostFacts items={[[t('disposition.currentHash'),<code>{row.current_hash??'—'}</code>],[t('disposition.retainedHash'),<code>{row.retained_hash}</code>],[t('disposition.recordedError'),<code>{row.recorded_error??'—'}</code>],[t('disposition.retainedError'),<code>{row.retained_error??'—'}</code>]]} />{row.current?<PriceCostBreakdown cost={row.current} title={t('cost.effective')} />:<p>{t('disposition.noReceipt')}</p>}<PriceCostBreakdown cost={row.retained} title={t('disposition.retained')} />{row.original&&<details><summary>{t('cost.original')}</summary><PriceCostBreakdown cost={row.original} title={t('cost.original')} /></details>}</div></details>)}{basis.receipts.length>size&&<div className="flex justify-between"><Button variant="ghost" disabled={!page} onClick={()=>setPage(p=>p-1)}>{t('previous')}</Button><span>{page+1}</span><Button variant="ghost" disabled={(page+1)*size>=basis.receipts.length} onClick={()=>setPage(p=>p+1)}>{t('next')}</Button></div>}</CardStatic><CardStatic className="space-y-4 p-5"><details><summary className="cursor-pointer text-sm font-semibold">{t('disposition.related',{count:basis.related_outcomes.length})}</summary><p className="my-3 text-xs leading-6">{t('disposition.inventoryHelp')}</p><ul className="max-h-80 space-y-3 overflow-y-auto">{basis.related_outcomes.map(row=><li key={row.id} className="space-y-1 border-l border-[var(--border)] pl-3 text-xs"><Link to={`/pricing/outcomes/${encodeURIComponent(row.id)}`} className="break-all font-mono underline">{row.id}</Link><p>{t(`disposition.state.${row.state}`)} · {row.disposition?t(`disposition.decision.${row.disposition}`):t('disposition.undecided')}</p></li>)}</ul></details></CardStatic></>
}
