import { PriceMeteringReview } from './price-metering-review'
import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import { Save, ShieldCheck, Upload, Download, Copy } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { PriceInput, PriceSelect } from './pricing-fields'
import { RuleSelector, RuleConditionEditor, PriceRatesEditor, BillingDimensionsEditor } from './price-rules-editor'
import { PriceParentPicker } from './price-parent-picker'
import { PriceInheritancePanel } from './price-inheritance-panel'
import { inheritedDefinition, priceExport, samePriceValue, verifyInheritancePreview, verifyParentPrice, type InheritancePreview, type ParentPrice, type PriceCopy } from '@/lib/price-inheritance-form'
import { PriceCalendarEditor } from './price-calendar-editor'
import { PriceSimulator, PricingDiagnostics, pricingErrorKey } from './price-simulator'
import { PricePublishDialog } from './price-publish-dialog'
import { usePricingNavigationState } from './pricing-navigation-guard'
import { pricingClient, PricingApiError } from '@/lib/pricing-client'
import { changedPaths, downloadPricing, mediaDimensions, pricingTabs, tokenDimensions, type PricingTab } from '@/lib/pricing-model'
import type { PriceBookDetail, PriceBookContent, PricingDraft, PriceValidation, PricingDiagnostic, PricingAuditEntry, PricingInheritanceView, PricingInheritanceDefinition } from '@/types/pricing'

const MediaSpecificationEditor = lazy(() => import('./media-specification').then(module => ({ default: module.MediaSpecificationEditor })))
const CalendarWeekPreview = lazy(() => import('./calendar-week-preview').then(module => ({ default: module.CalendarWeekPreview })))
const ContextRangeTable = lazy(() => import('./context-range-table').then(module => ({ default: module.ContextRangeTable })))

export function PriceBookEditor({ workspace, detail, initial, canEdit, choice, initialNode, initialModel, initialOperation, onChoice, onRefresh, onCopy }: { workspace: string; detail: PriceBookDetail; initial: { content: PriceBookContent; id?: string; revision?: number; version_id?: string; inheritance?: PricingInheritanceView }; canEdit: boolean; choice: string; initialNode?: string; initialModel?: string; initialOperation?: string; onChoice: (choice: string, completed?: boolean) => void; onRefresh: () => void; onCopy?: (value:PriceCopy) => void; }) {
  const { t, i18n } = useTranslation('pricing'), request = useMemo(() => pricingClient(workspace), [workspace])
  const [content, setContent] = useState(() => structuredClone(initial.content)), [saved, setSaved] = useState(() => structuredClone(initial.content)), [revision, setRevision] = useState(initial.revision ?? 0)
  const [inheritance, setInheritance] = useState(initial.inheritance), [recipe,setRecipe] = useState<PricingInheritanceDefinition|undefined>(initial.inheritance?.definition), [savedRecipe,setSavedRecipe] = useState(initial.inheritance?.definition), [stagedParent,setStagedParent] = useState<ParentPrice|undefined>()
  const [tab, setTab] = useState<PricingTab>('basic'), [group, setGroup] = useState(0), [rule, setRule] = useState(0)
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [stale, setStale] = useState(false)
  const feedback = useRef<HTMLDivElement>(null)
  useEffect(() => { if (error || notice) { feedback.current?.scrollIntoView({ block: 'center' }); feedback.current?.focus({ preventScroll: true }) } }, [error, notice])
  const [validation, setValidation] = useState<PriceValidation | null>(null), [diagnostics, setDiagnostics] = useState<PricingDiagnostic[]>([])
  const [remote, setRemote] = useState<Pick<PricingDraft, 'revision' | 'content' | 'inheritance'> | null>(null), [publish, setPublish] = useState<{ rollback?: string } | null>(null)
  const dirty = JSON.stringify(content) !== JSON.stringify(saved) || !samePriceValue(recipe,savedRecipe), draftId = initial.id
  const editable = canEdit && Boolean(draftId)
  const parentReference=recipe?.parent??inheritance?.definition.parent
  const parentQuery=useQuery({queryKey:['pricing',workspace,'immutable-parent',parentReference?.book_id,parentReference?.version_id,parentReference?.content_hash],queryFn:async({signal})=>verifyParentPrice(await request<ParentPrice>(`/books/${encodeURIComponent(parentReference!.book_id)}/versions/${encodeURIComponent(parentReference!.version_id)}`,undefined,'GET',signal),parentReference!),enabled:Boolean(parentReference),retry:false,staleTime:Infinity})
  const parent=stagedParent && samePriceValue({book_id:stagedParent.book_id,version_id:stagedParent.version_id,content_hash:stagedParent.content_hash},parentReference)?stagedParent:parentQuery.data
  const inheritanceLoading=Boolean(inheritance&&!parent)

  const g = Math.min(group, content.groups.length - 1), r = Math.min(rule, content.groups[g].rules.length - 1)
  const runtime = useQuery({ queryKey: ['pricing', workspace, 'calendar-runtime'], queryFn: ({ signal }) => request<{ tzdb_version: string; today: string }>('/calendar/runtime', undefined, 'GET', signal), staleTime: 60000 })
  const audit = useQuery({ queryKey: ['pricing', workspace, 'audit', detail.book.id], queryFn: ({ signal }) => request<PricingAuditEntry[]>(`/audit?book_id=${encodeURIComponent(detail.book.id)}&limit=50`, undefined, 'GET', signal), enabled: tab === 'versions' })
  usePricingNavigationState(dirty, busy)
  useEffect(() => {
    // A cached draft can be followed by a newer server revision after navigation/refresh.
    // Never discard local edits or regress to an older cached response.
    if (!draftId || initial.revision === undefined || initial.revision <= revision || busy) return
    if (dirty) { setStale(true); setRemote({ revision: initial.revision, content: initial.content, inheritance:initial.inheritance }); return }
    setContent(structuredClone(initial.content)); setSaved(structuredClone(initial.content)); setRevision(initial.revision); setInheritance(initial.inheritance); setRecipe(initial.inheritance?.definition); setSavedRecipe(initial.inheritance?.definition); setStagedParent(undefined)
    setValidation(null); setDiagnostics([]); setNotice(''); setError(''); setStale(false); setRemote(null)
  }, [draftId, initial.revision, initial.content, initial.inheritance, revision, busy, dirty])
  const change = (next: PriceBookContent,reset?:{component?:string;group?:string;calendar?:boolean;specification?:boolean}) => {
    if(inheritance){if(!parent)return;try{const updated=inheritedDefinition(parent,next,{content,inheritance:{...inheritance,definition:recipe??inheritance.definition}},reset);if(updated.calendar.mode==='replace'&&!next.time_basis)next={...next,time_basis:updated.calendar.time_basis};setRecipe(updated)}catch{setError(t('inheritance.invalid'));return}}
    setContent(next); setValidation(null); setNotice('')
  }
  const failed = (failure: unknown) => { setError(t(failure instanceof Error&&failure.message==='invalid_price_inheritance'?'inheritance.invalid':pricingErrorKey(failure))); if (failure instanceof PricingApiError) { setDiagnostics(failure.diagnostics); if (failure.status === 409) setStale(true) } }
  const resolvedPreview=async()=>{
    if(!recipe)throw new Error('invalid_price_inheritance')
    const [preview,materialized]=await Promise.all([request<InheritancePreview>('/inheritance/preview',{book_id:detail.book.id,definition:recipe}),request<PriceValidation>('/import/validate',{format:'siftgate-price-book-v1',content})])
    if(!materialized.valid||materialized.content_hash!==preview.content_hash)throw new Error('invalid_price_inheritance')
    return verifyInheritancePreview(preview,recipe,materialized.content)
  }
  const validate = async () => { setBusy(true); setError(''); setDiagnostics([]); try {
    if(recipe&&canEdit){const result=await resolvedPreview();setValidation({...result,valid:true})}else setValidation(await request<PriceValidation>('/import/validate', { format: 'siftgate-price-book-v1', content }))
    setNotice(t(recipe&&!canEdit?'inheritance.readOnlyValidation':'validated'))
  } catch (failure) { failed(failure) } finally { setBusy(false) } }
  const save = async () => { if (!draftId || !editable || stale || inheritanceLoading) return; setBusy(true); setError(''); setDiagnostics([]); try {
    const expected=recipe?await resolvedPreview():undefined
    const next = recipe?await request<PricingDraft>(`/drafts/${encodeURIComponent(draftId)}/inheritance`,{revision,definition:recipe},'PUT'):await request<PricingDraft>(`/drafts/${encodeURIComponent(draftId)}`, { revision, content }, 'PUT')
    if(expected&&(!samePriceValue(next.content,expected.content)||!samePriceValue(next.inheritance,expected.inheritance)))throw new Error('invalid_price_inheritance')
    setContent(next.content);setSaved(structuredClone(next.content));setInheritance(next.inheritance);setRecipe(next.inheritance?.definition);setSavedRecipe(next.inheritance?.definition);setRevision(next.revision);setNotice(t('saved'));onRefresh()
  } catch (failure) { failed(failure) } finally { setBusy(false) } }
  const copy = async () => {if(!onCopy||busy)return;setBusy(true);setError('');try{const value=recipe&&dirty?await resolvedPreview():{content,inheritance};onCopy(structuredClone({content:value.content,inheritance:value.inheritance}))}catch(failure){failed(failure)}finally{setBusy(false)}}
  const fork = async (version: string) => { if (dirty && !window.confirm(t('discardConfirm'))) return; setBusy(true); try { const next = await request<PricingDraft>(`/books/${encodeURIComponent(detail.book.id)}/drafts`, { version_id: version }); onRefresh(); onChoice(`draft:${next.id}`, true) } catch (failure) { failed(failure) } finally { setBusy(false) } }
  const loadRemote = async () => { if (!draftId) return; try { setRemote(await request<PricingDraft>(`/drafts/${encodeURIComponent(draftId)}`)) } catch (failure) { failed(failure) } }
  return <article className="min-w-0">
    <header className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold tracking-tight">{detail.book.name}</h2><p className="mt-2 flex flex-wrap items-center gap-2 text-xs"><Badge variant={draftId ? 'amber' : 'emerald'}>{t(draftId ? 'draft' : 'published')}</Badge><span className="font-mono">{draftId ? t('revision', { revision }) : initial.version_id?.slice(0, 12)}</span>{dirty && <Badge variant="amber">{t('unsaved')}</Badge>}</p></div><div className="flex flex-wrap gap-2">{onCopy&&<Button variant="outline" size="sm" disabled={busy||inheritanceLoading} onClick={()=>void copy()}><Copy className="h-3.5 w-3.5"/>{t('copy')}</Button>}<Button variant="outline" size="sm" disabled={busy} onClick={() => downloadPricing(priceExport(content,recipe), draftId ? 'pricing-draft' : 'pricing-version')}><Download className="h-3.5 w-3.5" />{t(draftId ? 'exportDraft' : 'exportVersion')}</Button></div></header>
    <p className="mb-5 flex gap-2 text-xs leading-5 text-[var(--foreground-muted)]"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0" />{t('draftSafety')}</p>
    <div className="mb-5 overflow-x-auto border-b border-[var(--border)]"><div role="tablist" aria-label={t('editor.sections')} className="flex min-w-max gap-1">{pricingTabs.map((item, index) => <button type="button" key={item} role="tab" aria-selected={tab === item} id={`pricing-tab-${item}`} aria-controls="pricing-editor-panel" tabIndex={tab === item ? 0 : -1} onClick={() => setTab(item)} onKeyDown={(event) => { if (event.key === 'ArrowRight' || event.key === 'ArrowLeft') { event.preventDefault(); const next = pricingTabs[(index + (event.key === 'ArrowRight' ? 1 : -1) + pricingTabs.length) % pricingTabs.length]; setTab(next); document.getElementById(`pricing-tab-${next}`)?.focus() } }} className={`border-b-2 px-3 py-3 text-xs font-semibold transition-colors ${tab === item ? 'border-[var(--accent)] text-[var(--accent)]' : 'border-transparent text-[var(--foreground-muted)] hover:bg-[var(--accent-muted)]'}`}>{t(`tab.${item}`)}</button>)}</div></div>
    <div ref={feedback} tabIndex={-1}>{error && <p role="alert" className="mb-4 text-sm text-[var(--destructive)]">{error}</p>}{notice && <p role="status" className="mb-4 text-sm text-[var(--accent)]">{notice}</p>}<PricingDiagnostics diagnostics={diagnostics} /></div>
    {stale && <section className="my-4 space-y-3 rounded-lg border border-amber-500/30 p-4"><p className="text-sm">{t('conflictHelp')}</p><Button size="sm" variant="outline" onClick={() => void loadRemote()}>{t('compareLatest')}</Button>{remote && <><p className="text-xs">{t('changedPaths')}</p><ul className="text-xs">{changedPaths({content:remote.content,definition:remote.inheritance?.definition},{content,definition:recipe}).map((path) => <li key={path}><code>{path}</code></li>)}</ul><Button variant="outline" size="sm" onClick={() => { if (!window.confirm(t('discardConfirm'))) return; setContent(remote.content); setSaved(structuredClone(remote.content)); setRevision(remote.revision); setInheritance(remote.inheritance);setRecipe(remote.inheritance?.definition);setSavedRecipe(remote.inheritance?.definition);setStagedParent(undefined); setRemote(null); setStale(false); setError(''); setDiagnostics([]); setValidation(null) }}>{t('reloadLatest')}</Button></>}</section>}
    {inheritance&&<div className="my-5"><PriceInheritancePanel view={inheritance} definition={recipe} content={content} parent={parent} disabled={!editable||busy||stale||inheritanceLoading} onChange={change}/>{inheritanceLoading&&<p role={parentQuery.error?'alert':'status'} className="mt-3 text-sm">{t(parentQuery.error?'inheritance.parentUnavailable':'inheritance.loadingParent')}{parentQuery.error&&<Button variant="link" size="sm" disabled={busy||parentQuery.isFetching} onClick={()=>void parentQuery.refetch()}>{t('refresh')}</Button>}</p>}</div>}
    {editable&&<div className="my-5"><PriceParentPicker workspace={workspace} scope={detail.book.workspace_id===null?'global':'workspace'} childId={detail.book.id} disabled={busy||stale} onBusy={setBusy} onStage={(preview,selected)=>{setInheritance(preview.inheritance);setRecipe(preview.inheritance.definition);setStagedParent(selected);setContent(preview.content);setGroup(0);setRule(0);setValidation(null);setNotice('');setError('');setDiagnostics([])}}/></div>}
    <div id="pricing-editor-panel" role="tabpanel" aria-labelledby={`pricing-tab-${tab}`} className="space-y-5">
      {tab !== 'simulate' && tab !== 'versions' && <>
        <RuleSelector content={content} groupIndex={g} ruleIndex={r} select={(group, rule) => { setGroup(group); setRule(rule) }} onChange={change} disabled={!editable || busy || stale || inheritanceLoading} />
        {!editable && <p className="text-xs text-[var(--foreground-muted)]">{t('readOnly')}</p>}
        <fieldset disabled={!editable || busy || stale || inheritanceLoading} className="min-w-0 space-y-5 disabled:opacity-80">
          {tab === 'basic' && <><div className="grid gap-4 sm:grid-cols-2"><PriceInput label={t('currency')} disabled={Boolean(inheritance)} maxLength={3} value={content.currency} onChange={(e) => change({ ...content, currency: e.target.value.toUpperCase() })} /><PriceInput label={t('precision')} type="number" min={0} max={18} value={content.money_precision} onChange={(e) => change({ ...content, money_precision: Number(e.target.value) })} /><PriceSelect label={t('moneyRounding')} value={content.money_rounding} options={['half_even', 'half_up', 'ceil', 'floor'].map((value) => ({ value, label: t(`round.${value}`) }))} onChange={(value) => change({ ...content, money_rounding: value as PriceBookContent['money_rounding'] })} /><PriceSelect label={t('source')} value={content.source.kind} options={['manual', 'approved_catalog', 'reference', 'legacy'].map((value) => ({ value, label: t(`source.${value}`) }))} onChange={(value) => change({ ...content, source: { ...content.source, kind: value as PriceBookContent['source']['kind'] } })} /><PriceInput label={t('sourceReference')} value={content.source.reference ?? ''} onChange={(e) => change({ ...content, source: { ...content.source, reference: e.target.value || undefined } })} /><PriceInput label={t('verifiedAt')} value={content.source.verified_at ?? ''} onChange={(e) => change({ ...content, source: { ...content.source, verified_at: e.target.value || undefined } })} /></div><BillingDimensionsEditor content={content} onChange={change} dimensions={tokenDimensions} /><PriceRatesEditor content={content} groupIndex={g} ruleIndex={r} onChange={change} dimensions={tokenDimensions} /></>}
          {tab === 'context' && <><Suspense fallback={<p role="status" className="text-xs">{t('working')}</p>}><ContextRangeTable content={content} groupIndex={g} ruleIndex={r} select={index => setRule(index)} onChange={change} disabled={!editable || busy || stale || inheritanceLoading} /></Suspense><RuleConditionEditor content={content} groupIndex={g} ruleIndex={r} onChange={change} kind="context" /><PriceRatesEditor content={content} groupIndex={g} ruleIndex={r} onChange={change} dimensions={content.billing_dimensions} /></>}
          {tab === 'time' && <><RuleConditionEditor content={content} groupIndex={g} ruleIndex={r} onChange={change} kind="time" /><PriceCalendarEditor calendar={content.calendar} timeBasis={content.time_basis} runtime={runtime.data} onChange={(calendar) => change({ ...content, calendar, time_basis: calendar ? content.time_basis : undefined })} onBasis={(value) => change({ ...content, time_basis: value as PriceBookContent['time_basis'] })} /></>}
          {tab === 'media' && <><p className="text-xs leading-5 text-[var(--foreground-muted)]">{t('meteringWarning')}</p><Suspense fallback={<p role="status">{t('working')}</p>}><MediaSpecificationEditor content={content} onChange={change} parent={parent?.content} /></Suspense><BillingDimensionsEditor content={content} onChange={change} dimensions={mediaDimensions} /><RuleConditionEditor content={content} groupIndex={g} ruleIndex={r} onChange={change} kind="media" /><PriceRatesEditor content={content} groupIndex={g} ruleIndex={r} onChange={change} dimensions={mediaDimensions} /></>}
        </fieldset>
      </>}
      {tab === 'time' && content.calendar && <Suspense fallback={<p role="status" className="text-xs">{t('working')}</p>}><CalendarWeekPreview workspace={workspace} calendar={content.calendar} /></Suspense>}
      {tab === 'simulate' && <PriceSimulator workspace={workspace} content={content} published={detail.versions[0] ? { book_id: detail.book.id, version_id: detail.versions[0].version_id } : undefined} />}
      {tab === 'versions' && <div className="space-y-5"><h3 className="font-semibold">{t('versions.title')}</h3><div className="space-y-3">{detail.versions.map((version) => <div key={version.version_id} className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--border)] pb-3"><div><code className="text-xs">{version.version_id.slice(0, 12)}</code><p className="mt-1 text-xs text-[var(--foreground-muted)]">{new Date(version.published_at).toLocaleString(i18n.resolvedLanguage)} · {version.reason}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="ghost" onClick={() => onChoice(`version:${version.version_id}`)}>{t('versions.view')}</Button><Button size="sm" variant="outline" disabled={!canEdit || busy} onClick={() => void fork(version.version_id)}>{t('versions.fork')}</Button><Button size="sm" variant="ghost" disabled={!canEdit || busy} onClick={() => { if (!dirty || window.confirm(t('discardConfirm'))) setPublish({ rollback: version.version_id }) }}>{t('publish.rollback')}</Button><Button size="sm" variant="ghost" onClick={() => { void request(`/books/${encodeURIComponent(detail.book.id)}/export?version_id=${encodeURIComponent(version.version_id)}`).then((value) => downloadPricing(value, 'pricing-version')).catch(failed) }}>{t('export')}</Button></div></div>)}</div>
        <h3 className="font-semibold">{t('versions.bindings')}</h3><ul className="space-y-3">{detail.bindings.map((binding) => <li key={binding.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md bg-[var(--background)] p-3 text-xs"><div><p className="font-mono">{binding.node_id ? `${binding.node_id} / ` : ''}{binding.model}</p><p className="mt-1 text-[var(--foreground-muted)]">{t(`level.${binding.level}`)} · {binding.operation ?? t('publish.allOperations')} · {binding.effective_from}{binding.effective_to ? ` → ${binding.effective_to}` : ''}</p></div>{new Date(binding.effective_from).getTime() > Date.now() && canEdit && <Button size="sm" variant="ghost" disabled={busy} onClick={async () => { const reason = window.prompt(t('publish.cancelReason')); if (!reason?.trim() || !window.confirm(t('removeConfirm'))) return; setBusy(true); try { const current = await request<{ head: { revision: number } }>('/bindings'); await request(`/bindings/${encodeURIComponent(binding.id)}/cancel`, { catalog_revision: current.head.revision, reason, confirm: true }); onRefresh() } catch (failure) { failed(failure) } finally { setBusy(false) } }}>{t('versions.cancelSchedule')}</Button>}</li>)}</ul>
        <h3 className="font-semibold">{t('versions.audit')}</h3>{audit.isError ? <p role="alert" className="text-xs text-[var(--destructive)]">{t('error.request')}</p> : <ul className="divide-y divide-[var(--border)]">{audit.data?.map((entry) => <li key={entry.id} className="py-3 text-xs"><p><code>{entry.action}</code> · {new Date(entry.created_at).toLocaleString(i18n.resolvedLanguage)}</p><p className="mt-1 text-[var(--foreground-muted)]">{entry.reason}</p></li>)}</ul>}
      </div>}
    </div>
    {validation && <div className="mt-5"><PricingDiagnostics diagnostics={validation.warnings} />{validation.metering && <PriceMeteringReview review={validation.metering} />}</div>}
    <footer className="sticky bottom-0 z-10 mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-[var(--border)] bg-[var(--background-secondary)] py-4"><div className="text-xs text-[var(--foreground-muted)]">{t(dirty ? 'unsaved' : 'savedState')}</div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={() => void validate()}>{t('validate')}</Button>{editable && <Button disabled={busy || stale || !dirty || inheritanceLoading} onClick={() => void save()}><Save className="h-3.5 w-3.5" />{t('saveDraft')}</Button>}{editable && <Button variant="secondary" disabled={busy || dirty || stale || inheritanceLoading} onClick={() => setPublish({})}><Upload className="h-3.5 w-3.5" />{t('publish.title')}</Button>}</div></footer>
    {publish && <PricePublishDialog workspace={workspace} detail={detail} draft={publish.rollback ? undefined : { id: draftId!, revision, content, inheritance, book_id: detail.book.id, created_by: '', created_at: '', updated_at: '' }} versionId={publish.rollback} initialModel={initialModel} initialNode={initialNode} initialOperation={initialOperation} onClose={() => setPublish(null)} onPublished={(version) => { setPublish(null); setNotice(t('publishedNotice')); onRefresh(); onChoice(`version:${version}`, true) }} />}
  </article>
}
